require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ================================
# react-native-permissions (v3+)
# ================================
require_relative '../node_modules/react-native-permissions/scripts/setup'

setup_permissions([
  'Camera',
  'PhotoLibrary',
  'Microphone',
  'LocationWhenInUse',
  'LocationAlways',
  'Contacts',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'showa' do
  config = use_native_modules!

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
