name: Android APK Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Xmx4g -XX:MaxMetaspaceSize=1g

    steps:

      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install dependencies (always run)
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 5️⃣ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 6️⃣ Setup keystore
      - name: Setup Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/release.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # 7️⃣ Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 8️⃣ Generate React Native bundle
      - name: Generate JS bundle
        run: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      # 9️⃣ Clean Gradle
      - name: Clean Gradle
        run: |
          cd android
          ./gradlew clean

      # 🔟 Build Release APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug


      # 1️⃣1️⃣ Upload APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
